FROM python:3.9-slim AS builder

WORKDIR /app

COPY app.py config.py firebase-key.json /app/
COPY static /app/static
COPY templates /app/templates
RUN pip install --no-cache-dir --target=/app/deps Flask requests firebase_admin

FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /app/deps /app/deps
COPY --from=builder /app /app

ENV PYTHONPATH=/app/deps

EXPOSE 5000

CMD ["python", "app.py"]