

# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set environment variables to prevent Python from writing .pyc files and buffering stdout
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Install necessary system dependencies (git, etc.)
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean

# Clone the CLIP repository and install dependencies
RUN git clone https://github.com/openai/CLIP.git /app/CLIP
WORKDIR /app/CLIP
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -e .
RUN pip install transformers
RUN pip install scikit-learn
RUN pip install sentencepiece
RUN pip install protobuf
RUN pip install numpy
RUN pip install requests
RUN pip install sacremoses


# Install Flask and other dependencies for image processing
RUN pip install Flask Pillow torch

# Copy the local model directory into the container
COPY flan_t5_trained_model /app/flan_t5_trained_model

# Copy the server script (ai_server.py) into the container
COPY ai_server.py /app/

# Expose Flask port
EXPOSE 6000

# Set the working directory
WORKDIR /app

# Set the command to run your Flask app
CMD ["python", "ai_server.py"]
